### ISSUE TITLE
NaNs or similar during final steps

### ISSUE THREAD

**Issue by ekernf01** [dylkot/cNMF#1]
Hi cNMF authors,

I am having some trouble with the last two steps. The error is:

```
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

Sometimes it affects stability plotting, sometimes the consensus step, and sometimes both or neither. Here is a minimal example where both are affected. 

[cnmf_nan.zip](https://github.com/dylkot/cNMF/files/3492802/cnmf_nan.zip)

Thanks for making this great tool public!

**Comment by dylkot** [comment]
Hi there! Thanks for the kind words. 

My guess is that this issue is caused when the input counts matrix includes a cell or gene that has no counts. Is that the case for you? Can you copy the sequence of commands you are running? Thanks!

**Comment by ekernf01** [comment]
Hi Dylan, 

Thanks for the quick response! Here are the commands I used. There are probably some empty genes, so I will try removing those.

```
     source activate cnmf_env 
     pip freeze > requirements.txt
     python -V 2> python_version.txt
     proj_dir="/Users/EricKernfeld/Desktop/cnmf_nan"
     cd $proj_dir
     input=test.tsv
     output=cnmf_out
     name=test
     cnmf="/Users/EricKernfeld/Desktop/programs/cnmf.py"
     
     python ${cnmf} prepare \
         --output-dir ${output} \
         --name ${name} \
         -c ${input} \
         -k 5 6 7 8 9 10 \
         --n-iter 100 \
         --total-workers 1 \
         --seed 14 \
         --numgenes 20

     python ${cnmf} factorize \
        --output-dir ${output} \
        --name ${name} \
        --worker-index 0 
        
    python ${cnmf} combine \
        --output-dir ${output} \
        --name ${name} \

    python ${cnmf} k_selection_plot \
        --output-dir ${output} \
        --name ${name} \
        
    python ${cnmf} consensus \
        --output-dir ${output} \
        --name ${name} \
        --components 5 \
        --local-density-threshold 0.1
	source deactivate cnmf_env

```

**Comment by ekernf01** [comment]
Unfortunately, I still have the problem after removing non-expressed genes and cells. Here is an example script with version info and test data:

[cnmf_nan.zip](https://github.com/dylkot/cNMF/files/3493445/cnmf_nan.zip)

Here is the full error. 

```
Traceback (most recent call last):
  File "/Users/EricKernfeld/Desktop/programs/cnmf.py", line 744, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering, args.stats_only)
  File "/Users/EricKernfeld/Desktop/programs/cnmf.py", line 511, in consensus
    topic_labels=np.arange(1,k+1))
  File "/Users/EricKernfeld/Desktop/programs/cnmf.py", line 285, in _nmf
    (W, H, niter) = non_negative_factorization(X.values, **nmf_kwargs)
  File "//anaconda/envs/cnmf_env/lib/python3.6/site-packages/sklearn/decomposition/nmf.py", line 1017, in non_negative_factorization
    _check_init(H, (n_components, n_features), "NMF (input H)")
  File "//anaconda/envs/cnmf_env/lib/python3.6/site-packages/sklearn/decomposition/nmf.py", line 60, in _check_init
    A = check_array(A)
  File "//anaconda/envs/cnmf_env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 568, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "//anaconda/envs/cnmf_env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by dylkot** [comment]
OK I have recapitulated the error with your test data. It seems like some cells are ending up with usage of 0 for all programs. 

It seems that your input data is not integer/count data and that cells have a median sum of ~80. Did you do any normalization prior to running cNMF?

**Comment by ekernf01** [comment]
Yes. I scaled each cell to a count of 10,000, then did log(x+1). This was originally a much larger matrix, and I took a subset of genes and a subset of cells to have a fast test example. Do you recommend something different?

I can sort of see why an unusual or shallow-sequenced gene or cell might have zero loadings for all components in NMF. I don't know if I can prevent that solely by manipulating the count matrix. One option would be to "spike" the final input matrix: for instance, I could add 1 to all entries, so that NMF should recover a component with a row vector of ones and a column vector of ones (approximately and disregarding some non-identifiable constants). The spike test works on my demo data, in the sense that it runs without errors, but none of the resulting components is constant across genes and cells. I tried adding 10000 as well, hoping the constant rank-1 component would be obvious, and that yielded close to constant results for all usages but not for any spectra.

**Comment by dylkot** [comment]
We typically do not normalize for library size (TPT) or log transform the data prior to cNMF. We don't TPT normalize because the usage matrix can account for the different library sizes of the cells. We skip the log transformation because we want the components to be additive in raw gene expression space, not multiplicative. To make sure low-expressed and high-expressed genes contribute comparable amounts of information, we variance scale the genes (but that is all done within the cnmf.py code).

Could you try running the pipeline starting from a raw count matrix without TPT or log transformation? My guess is that this will fix the problem. I don't think you should have to do any manipulation of the count matrix of the type you suggest. But if that doesn't fix it, we can go from there. Also, if it doesn't fix it, can you send me the raw count data? Thanks!

**Comment by ekernf01** [comment]
It sounds like we're getting towards the bottom of this, but I am confused about one thing. In the jupyter notebook tutorial, you have a section near the start entitled "Prepare the normalized count matrix of highvar genes and the cNMF parameters file". What's going into that step and coming out of it? Does the input have completely raw counts with all genes, and the output have a subset of high-variance genes, but with each gene scaled to unit variance? Or does the input already have each gene scaled to unit variance?

**Comment by ekernf01** [comment]
Both ways, I get past the `NaN` error, but I get a different error:

```
Traceback (most recent call last):
  File "/Users/EricKernfeld/Desktop/programs/cnmf.py", line 744, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering, args.stats_only)
  File "/Users/EricKernfeld/Desktop/programs/cnmf.py", line 434, in consensus
    kmeans_model.fit(l2_spectra)
  File "//anaconda/envs/cnmf_env/lib/python3.6/site-packages/sklearn/cluster/k_means_.py", line 968, in fit
    return_n_iter=True)
  File "//anaconda/envs/cnmf_env/lib/python3.6/site-packages/sklearn/cluster/k_means_.py", line 315, in k_means
    _num_samples(X), n_clusters))
ValueError: n_samples=1 should be >= n_clusters=5
```

Here is the example, including the demo count matrix. 

[cnmf_nan.zip](https://github.com/dylkot/cNMF/files/3493858/cnmf_nan.zip)

(Do you mind that I keep this new error on the same issue thread? It seems likely to be related.)

**Comment by ekernf01** [comment]
A couple more tests suggest that it will run fine on raw counts as long as low-expressed genes are excluded. (I.e. don't estimate a spectrum coefficient for a gene with only one or two UMIs.) That seems reasonable anyways, and I'll go ahead and try cnmf on the full data while filtering a little more aggressively. 

Thanks for all your help today!

**Comment by dylkot** [comment]
So with your new input data, I am actually not getting the same error you saw but I am still getting a 

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

error on the consensus step. The reason for this is that there seem to be 2 cells that don't have a single count of the 20 highest variance genes which leads to the crash. Those cells are:

AACTGGTAGAATTGTG|CR_pharynx_E9_5_rep1
ACATACGAGAGCTGGT|CR_pharynx_E9_5_rep1

After filtering those an running the pipeline, it goes to completion without issue and the results look sensible.

Essentially this wasn't a situation I anticipated, so I should update the code to not throw an error in such cases but rather to return the usages with all NaNs for those cells. I will make sure this is in the updated version of the code. For your situation, I bet that if you scale this up to the full dataset and >1000 high-variance genes, it shouldn't be a problem as long as you are filtering out cells with <500 or so counts detected.

And regarding your earlier question, PREPARE expected raw counts matrix as an input and saves a file containing only the high-variance genes and the genes all scaled to unit variance.

**Comment by danshu** [comment]
@dylkot  Have you updated your code for this issue? I'm having the same error on raw counts of my scRNA data, and I guess this is caused by the low sequencing depth. 
BTW, what are recommended sequencing depth for cNMF? I'm working on a 10x scRNA dataset with nGene >= 200. 

Best,
Danshu

**Comment by dylkot** [comment]
Hi Danshu,

In the case of the error above, part of the problem was potentially due to the fact that the data was being log normalized before cNMF which it shouldn't be.

The other issue was related to the fact that some cells didn't have a single count of any of the over-dispersed genes that were being used for the NMF runs. One way around this would be to provide your own set of over-dispersed genes with the --genes_file option for the 'prepare' step and to confirm that each cell in your input data has at least one count of at least one of the genes in that file (and to filter out any cells that have no counts of any of those genes). As of right now, the only updates to the code I'm planning to make are to make the error message more interpretable and to give a warning message at the end of the prepare step to indicate that this is happening.

Regarding number of genes, I have been able to run the method quite productively for a dataset with nGene >= 200. However, the larger the depth the better for getting finely resolved activity programs.

**Comment by danshu** [comment]
@dylkot  Thanks!

**Comment by dylkot** [comment]
The warning is now added in the latest commit on the development branch
