### ISSUE TITLE
Step 5 Consensus command - TypeError: H should have the same dtype as X

### ISSUE THREAD

**Issue by jasminelmah** [dylkot/cNMF#10]
Hi authors!

First off, thanks for creating such a useful program. I am eager to use it!

I ran into an error that seems related to the one mentioned in https://github.com/dylkot/cNMF/issues/9#issue-714097555 and https://github.com/dylkot/cNMF/issues/8#issue-651940726. In those issues, the error `TypeError: H should have the same dtype as X` arose when trying to create the k selection plot using the command `python ./cnmf.py k_selection_plot`. I added `norm_counts.X = norm_counts.X.astype(np.float64)` to cnmf.py line 503, as suggested by Pentayouth [here](https://github.com/dylkot/cNMF/issues/8#issuecomment-686444543), and this resolved the issue.

I have now run into the same problem with the command in step 5 of the README.

Command: `python3 ./cnmf.py consensus --output-dir ./example_data --name example_cNMF --components 10 --local-density-threshold 0.01 --show-clustering`

Traceback:

> (base) vpn1722517526:example_PBMC jasmineliannemah$ python3 ./cnmf.py consensus --output-dir ./example_data --name example_cNMF --components 10 --local-density-threshold 0.01 --show-clustering
/Library/Python/3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.decomposition.nmf module is deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
warnings.warn(message, FutureWarning)
Traceback (most recent call last):
File "./cnmf.py", line 882, in
cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering)
File "./cnmf.py", line 558, in consensus
nmf_kwargs=refit_nmf_kwargs)
File "./cnmf.py", line 410, in _nmf
(usages, spectra, niter) = non_negative_factorization(X, **nmf_kwargs)
File "/Library/Python/3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
return f(**kwargs)
File "/Library/Python/3.7/site-packages/sklearn/decomposition/_nmf.py", line 1044, in non_negative_factorization
"{}.".format(H.dtype))
TypeError: H should have the same dtype as X. Got H.dtype = float64.

Any idea how to resolve this issue? Thanks!

**Comment by jasminelmah** [comment]
I forgot to add: here is the example data I was working with. I tried it with my own data, starting from a normal UMI counts table (not a .h5ad file) and ran into the same error. Let me know if you need anything else to reproduce the error. 
[counts.h5ad.zip](https://github.com/dylkot/cNMF/files/5435525/counts.h5ad.zip)

**Comment by dylkot** [comment]
Awesome, thanks I'll take a look today

**Comment by sjessa** [comment]
Hello,

I also encountered this error and was able to resolve it using a similar solution as in #8 / #9 by editing the `_nmf` function to cast the dtype of X to 'float64':

```python
 def _nmf(self, X, nmf_kwargs):
        """
        Parameters
        ----------
        X : pandas.DataFrame,
            Normalized counts dataFrame to be factorized.

        nmf_kwargs : dict,
            Arguments to be passed to ``non_negative_factorization``

        """

        # Following https://github.com/dylkot/cNMF/issues/8#issue-651940726
        # to resolve an error
        X = X.astype(np.float64)
        (usages, spectra, niter) = non_negative_factorization(X, **nmf_kwargs)

        return(spectra, usages)
```

**Comment by jasminelmah** [comment]
Thanks sjessa! 

It seems to run now, but with many warnings. They are:

Step 1:
`module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
sys:1: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
/Library/Python/3.7/site-packages/anndata/_core/anndata.py:1094: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  if not is_categorical(df_full[k]):
/Library/Python/3.7/site-packages/scanpy/preprocessing/_simple.py:806: UserWarning: Revieved a view of an AnnData. Making a copy.
  view_to_actual(adata)`

Step 2:
`/Library/Python/3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.decomposition.nmf module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
[Worker 0]. Starting task 0.
/Library/Python/3.7/site-packages/numpy/lib/format.py:350: UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
  d['descr'] = dtype_to_descr(array.dtype)`

Step 3:
`/Library/Python/3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.decomposition.nmf module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
Combining factorizations for k=5.
/Library/Python/3.7/site-packages/numpy/lib/format.py:350: UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
  d['descr'] = dtype_to_descr(array.dtype)`

Step 4:
`/Library/Python/3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.decomposition.nmf module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)`

Step 5:
`/Library/Python/3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.decomposition.nmf module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
/Library/Python/3.7/site-packages/numpy/lib/format.py:350: UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
  d['descr'] = dtype_to_descr(array.dtype)
/Library/Python/3.7/site-packages/numpy/lib/format.py:350: UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
  d['descr'] = dtype_to_descr(array.dtype)`

None of these proved fatal, as everything ran, but is there anything here I should be alarmed about Dylan? Thanks for your help!

**Comment by dylkot** [comment]
Sorry for the slow reply. Those should all be fine! 

I updated the code to check if the dtype needs to be changed for the TPM and normalized counts matrices and confirmed that it runs on your data so this should all be set now. Good luck with your analysis and I hope cNMF is helpful for you!

**Comment by jasminelmah** [comment]
Thank you! I appreciate it!

**Comment by njh219** [comment]
Had the same issues as above.
Utilized the solution as mentioned; X = X.astype(np.float64). 
However, I am now getting a new error wherein the H.dtype is in float32 when running consensus. Very unclear why this would come up. Working on a 64-bit windows/python install. 
I've attached snips of the error from prior to using the above solution and after. 

cnmf_obj.consensus(k=selected_K, density_threshold=density_threshold, show_clustering=True, close_clustergram_fig=False)
![image](https://user-images.githubusercontent.com/12008770/177197039-1faca30b-21bb-4deb-9dd6-10bff03f504a.png)
![image](https://user-images.githubusercontent.com/12008770/177197063-31123bef-84be-4e21-9827-a84d30690e28.png)


TypeError: H should have the same dtype as X. Got H.dtype = float32.

**Comment by njh219** [comment]
Had the same issues as above.
Utilized the solution as mentioned; X = X.astype(np.float64).
However, I am now getting a new error wherein the H.dtype is in float32 when running consensus. 

After doing some review it seems that this is an error inherent to utilizing Numpy on Windows. Essentially, Numpy creates integers calling C Long which is inherently 32-bit (even on a 64-bit machine). As such, a small modification to the NMF Scikit-learn code is required. 
def _check_w_h needs to have a line added (line 1472) to explicitly create the non-negative matrix as 64-bit.
H = H.astype(np.float64) 
Posting here in case anyone else is running into the same issue.

**Comment by lzlyjya** [comment]
Thanks for your answer, but i am encountering the same issue as you, and the scripy of cnmf.py doesnot reach 1472 lines. It only has 1059 lines, could you help me with this? I would appreciate that

**Comment by njh219** [comment]
Use the find function in **NMF Scikit-learn script** for def _check_w_h, then add the line of code as mentioned. It will be in a different line depending on version. 
Make sure you are in the correct file.

**Comment by lzlyjya** [comment]
It worked!!!!  Thank you so much~

**Comment by qinting** [comment]
@njh219 Could you please clarify where `H = H.astype(np.float64)` should be added in the `_check_w_h` function (within `_nmf.py` file)? I tried to added it at the end of that function, but still got "TypeError: H should have the same dtype as X. Got H.dtype = float32."

```
    def _check_w_h(self, X, W, H, update_H):
        n_samples, n_features = X.shape
        if self.init == "custom" and update_H:
            _check_init(H, (self._n_components, n_features), "NMF (input H)")
            _check_init(W, (n_samples, self._n_components), "NMF (input W)")
            if H.dtype != X.dtype or W.dtype != X.dtype:
                raise TypeError(
                    "H and W should have the same dtype as X. Got "
                    "H.dtype = {} and W.dtype = {}.".format(H.dtype, W.dtype)
                )
        elif not update_H:
            _check_init(H, (self._n_components, n_features), "NMF (input H)")
            if H.dtype != X.dtype:
                raise TypeError(
                    "H should have the same dtype as X. Got H.dtype = {}.".format(
                        H.dtype
                    )
                )
            # 'mu' solver should not be initialized by zeros
            if self.solver == "mu":
                avg = np.sqrt(X.mean() / self._n_components)
                W = np.full((n_samples, self._n_components), avg, dtype=X.dtype)
            else:
                W = np.zeros((n_samples, self._n_components), dtype=X.dtype)
        else:
            W, H = _initialize_nmf(
                X, self._n_components, init=self.init, random_state=self.random_state
            )
        **H = H.astype(np.float64)**
        return W, H
```
P.S. I also tried to add the code right below the "def _check_w_h(self, X, W, H, update_H):" line, but got KeyError(f"None of [{key}] are in the [{axis_name}]")

Thanks for your help!

**Comment by njh219** [comment]
Hi there.
Under _check_w_h, the second elif not state is as follows:
        elif not update_H:
            _check_init(H, (self._n_components, n_features), "NMF (input H)")

add the following line (in line with _check_init):
H = H.astype(np.float64)

Hopefully that solves the problem for you. 

Looking at your output you may have a different issue though. It seems that your keys are incorporating line breaks (\n) which should be sanitized when going into your array. May be more than one thing going on that isn't as attributable to the underlying _nmf.py script.

**Comment by qinting** [comment]
@njh219 Thanks so much for your help! It works now.
