### ISSUE TITLE
How to avoid the batch effect?

### ISSUE THREAD

**Issue by yuGithuuub** [dylkot/cNMF#11]
Hi cNMF authors,
I noticed that you strongly recommend using the original matrix as the input object. 
Will the batch effect affect the result?
Best  
Shizhe Yu

**Comment by dylkot** [comment]
Hi Shizhe,

I discuss this a bit in the eLIFE paper in figure 5 figure supplement 1: https://elifesciences.org/articles/43803#fig5s1

As you'd expect batch effect does seem to manifest in the final components if you analyze batch effected data. There isn't a simple solution to this. In the past, I have had some success regressing out the batch effect with COMBAT prior to cNMF. However, this creates some negative values so you have to set a floor by changing negative values to 0 which isn't ideal. In general, cNMF seems to work pretty well even in the setting of modest batch effect.

**Comment by yuGithuuub** [comment]
Hi Dylan :
  Thanks for your reply .
  The AIDA group suggests that stricter QC ,such like umi count >2000 ,could significantly reduce batch effects . I wonder that it may be helpful in cNMF  process too.
