### ISSUE TITLE
How to isolate RPL/RPS/MT- genes from an "identity" program?

### ISSUE THREAD

**Issue by Pentayouth** [dylkot/cNMF#13]
I'm reading your paper about consensus non-negative matrix factorization （cNMF）to distill biologically interpretable gene programs. Thank you very much for your work and the tool you developed.

I'm very interested in interpreting my single cell data with your tool. But questions arised in pratice which I also noticed in your tutorial provided [here](https://github.com/dylkot/cNMF/blob/master/Tutorials/analyze_pbmc_example_data.ipynb) . (**Tutorial for running cNMF on the 10X PBMC dataset used in the SEURAT and SCANPY tutorials.**)

First, I found you defined **GEP1 in Out[60]** as a T-cell identity program. Although I did see few genes like **CD3E, CD3D** in GEP1 and I believed the usages of the program across cells in **In [58]** is highly concordant with the presentation of T-cell population, It's hard not to notice the over-representation of ribosomal protein genes (PRL/RPS...) in **GEP1**.
To my knowledge and in the language of your paper, RPL/RPS genes form an "activity program" in charge of protein synthesis and should be widely used by different type of cells. It's a little bit weird to see T-cell marker genes and RPL genes mixed together in a GEP.

Second, I noticed the same issue in my data. In short, I have two tumor samples (A & B). I assumed:
**Sample A** has **"identity program" 1** and **"identity program" 2 (in abbr A1, A2)**, and
**Sample B** has **"identity program" 2 (in abbr B2) .**
In pratice with cNMF, I found:
**A1** has **"1"** marker genes with RPL/RPS genes ;
**A2** has **"2"** marker genes.
**B2** has **"2"** marker genes and RPL/RPS genes.
I further performed coorelation and clustering on those 3 programs. Although I want to see programs with similar identity (A1 and A2) highly correlated with each other and cluster together but instead the result showed **B2 has higher Pearson correlation with A1 than with A2, and A1 B2 clustered together**. 
I guess it is because RPL/RPS dominate A1 and B2, which makes them look like protein synthesis "activity program" rather than 2 distinct "identity program".

It wouldn't be a big deal if I just want to determine cell identity in one sample, but it caused some trouble when I analysed multiple samples and put all the GEPs togther to find something in common. Like **A1 and B2** cluster together for their similarity in **activity**, but what I really want to see is **A2 and B2** cluster together for their similarity in **identity**.

I wonder if RPL/RPS genes could be seperated from A1 and form an independent activity program, leaving a pure A1 identity program with "1" marker genes. I think it will make the program easier to interprete and more comparable between samples. But currently I don't know how to achieve that goal with cNMF.
Is removing ^RPS/^RPL/^MPRS/^MRPL genes (or ^MT- genes) from the count matrix a sensible preprocessing step in cNMF?

I'm not an expert in machine learning and statistics science and I'm not sure if my issue sounds naive to you. Any comments and suggestions are highly appreciated! Thank you!

Best.
Wang.

**Comment by Pentayouth** [comment]
I found those lines in your [paper](https://elifesciences.org/articles/43803#SA2)
> While in principle we could detect marker genes with separate tests for each GEP (e.g. by identifying genes with high Pearson correlation between the GEP usage and gene expression), this could suffer from confounding if GEPs are not independent. For example, if a gene is a marker of a cell-type that frequently expresses an activity program, there could be positive correlation between the activity usage and the gene’s expression, even if the gene isn’t directly associated with the activity. Including both the identity and activity GEP as covariates avoids this confounding and strengthens our testing approach.

So it probably explain the result I observed？

Best.
Wang.

**Comment by dylkot** [comment]
Hi Wang,

Sorry for the late reply. In general there is no simple way to know if a program is an activity or an identity program. It could hypothetically be a part of a highly translationally active cell-type's identity program to up-regulate a lot of ribosomal genes. However ribosomal genes could hypothetically also reflect artifacts such as ambient RNA (since there is a lot of rRNA in blood). Frequently mitochondrial gene levels are thought to reflect an artifact of sample processing and so are filtered out. I don't think there is as much of a precedent for filtering ribosomal genes but it is sometimes done. In any case, I hope this helps a little bit, good luck interpreting your data!
