### ISSUE TITLE
About import fastcluster error

### ISSUE THREAD

**Issue by hahia** [dylkot/cNMF#14]
when I run cnmf.py
![image](https://user-images.githubusercontent.com/49113803/119619442-94451980-be36-11eb-80cf-e36cde609c2e.png)
I can't import fastcluster, Can someone help me?

**Comment by dylkot** [comment]
Hi, did you set up the cnmfenv conda environment as specified in the instructions? Make sure you are launching the jupyter lab/notebook after you have activated the cnmfenv environment. Hope that helps!

**Comment by hahia** [comment]
> Hi, did you set up the cnmfenv conda environment as specified in the instructions? Make sure you are launching the jupyter lab/notebook after you have activated the cnmfenv environment. Hope that helps!

I set up the conda environment and just install the jupyterlab kernel in this environment. I can't run cnmf.py (import fastcluster error) in the jupyterlab but I can run the cnmf.py in the command line terminal. 
Thank you for your helo!!

**Comment by dylkot** [comment]
To run it from within the jupyterlab, you need the subsequent lines in the environment setup step:

```
conda install --yes jupyterlab==2.2.9 && conda clean --yes --all
```

Then you need to make sure you have activated the cnmfenv before launching jupyter lab. In any case, good luck!
