### ISSUE TITLE
Documentation issue with multiple workers and factorization?

### ISSUE THREAD

**Issue by jamesnemesh** [dylkot/cNMF#16]
Hi,

In the documentation and examples, it says
" However, if you specified more than 1 total worker, you would need to run the commands for those workers as well with separate commands, E.g.:

python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 1 
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 2
...
"

When I look at the code, the default number of workers is 1.  
parser.add_argument('--total-workers', type=int, help='[all] Total number of workers to distribute jobs to', default=1)

This gets passed into the function:
cnmf_obj.run_nmf(worker_i=args.worker_index, total_workers=args.total_workers)

This same strategy appears in the simulated data notebook:

qsub -cwd -b y -l h_vmem=2g,h_rt=3:00:00 -o ./log -e ./log -N cnmf -t 1-5 'python ../cnmf.py factorize --output-dir ./simulated_example_data --name example_cNMF --worker-index $SGE_TASK_ID'

This results in each worker running all the factorization jobs.   It might make sense to update the examples to pass in the --total-workers argument for the UGER factorization examples.   With that added argument, the code runs fine.

I was trying to figure out why a) The code is taking a while to run and b) factorization files were being overwritten with data from newer timestamps when from the code you write the output a single time per K/iteration.

**Comment by micans** [comment]
I found the same; the example on the loading page is
```
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 0 
```
If I add `--total-workers 20` (same as what I used that in the preparation step) then the  workers output a sub-selection of the jobs rather than computing everything.

**Comment by dylkot** [comment]
orry for the slow reply and yes you are totally right. I am hoping to push some updates that will hopefully clarify all of this so thanks for bringing it to my attention. You should specify the total number of workers as well 

```
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 0 --total-workers 5 &
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 1 --total-workers 5 &
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 2 --total-workers 5 &
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 3 --total-workers 5 &
python ./cnmf.py factorize --output-dir ./example_data --name example_cNMF --worker-index 4 --total-workers 5 &
```

to specify that there are 5 total workers and you want to run them sequentially.
