### ISSUE TITLE
cNMF produces warnings when writing npz files.

### ISSUE THREAD

**Issue by jamesnemesh** [dylkot/cNMF#17]
Hi,

I'm trying to run cNMF using the conda env as explained in the readme, and I'm encountering a warning.  I believe there's a very easy fix for this that I'm happy to submit a pull request for if you're interested.

1) The warning (factorize):
UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
     d['descr'] = dtype_to_descr(array.dtype)

Reproduce the error (at Broad on UGER interactive node):

Create conda env [don't include jupyter notebook]

conda create -n cnmf_env_baseline --yes --channel bioconda --channel conda-forge --channel defaults python==3.7 fastcluster==1.1.26 matplotlib==3.3.2 numpy==1.19.2 palettable==3.3.0 pandas==1.1.3 scipy==1.5.2 scikit-learn==0.23.2 pyyaml==5.3.1 scanpy==1.6.0 parallel && conda clean --yes --all

conda activate cnmf_env_baseline

Run cNMF steps:

python ${cNMF_dir}/cnmf.py prepare --output-dir ${outDir} --name ${outName} -c /path/to/small.transposed_filtered_dge.txt -k 5 6 7 
 --n-iter 10 --total-workers 1 --seed 14 --numgenes 2000

python ${cNMF_dir}/cnmf.py factorize --output-dir ${outDir} --name ${outName} --worker-index 0

1) The warning: 
When running factorize, it looks like there's a problem with save_df_to_npz, which shows up as a warning:

UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
     d['descr'] = dtype_to_descr(array.dtype)

In testing and slightly modifying your code, there's a quite fix to the save_df_to_npz function:
np.savez_compressed(filename, data=list(obj.values), index=list(obj.index.values), columns=list(obj.columns))

This converts the nparray to a simple list, to avoid the problem with encoding the dtype metadata.  

This warning occurs in other functions (eg: consensus).  I'm happy to share the input data with you directly if that's helpful.

**Comment by jamesnemesh** [comment]
FYI, I made a bunch of changes to the code both to improve reporting somewhat (a few extra outputs) and to make processing more memory efficient - normalizing the entire expression matrix to Z-scores blows up the memory usage, but you only need to do that in chunks.  We can submit the code we have as a pull request if you're interested.

**Comment by dylkot** [comment]
Hi @jamesnemesh - sure, that would be great if you don't mind, I'll take a look through. I have recently worked on restructuring the code to be more object oriented on the development branch. I can look into merging.
