### ISSUE TITLE
Is there a way to start running "factorize" from the latest spectra file instead of starting from the beginning

### ISSUE THREAD

**Issue by BW15061999** [dylkot/cNMF#18]

**Comment by BW15061999** [comment]
Hi,
After unexpected shutdown of my computer, is there a way to start the  _factorize_ from the latest spectra file in the _cnmf_tmp_ folder instead of rerunning from the beginning

**Comment by dylkot** [comment]
Hi, I'm sorry there currently isn't an easy way to do that. If you broke the job up into multiple workers (ideally to run them in parallel, but even if you run them sequentially), you can start the individual workers again that failed. But in general, we don't implement an easy way to restart from e.g. the 3rd task for a given worker.
