### ISSUE TITLE
get_highvar_genes_sparse function

### ISSUE THREAD

**Issue by ZohrehShams** [dylkot/cNMF#20]
Hi, 
This function uses two variables that are not defined: "gene_counts_fano" and "gene_counts_mean" . Shouldn't these be "gene_mean" and "gene_fano" instead? 
Thanks.

**Comment by dylkot** [comment]
I don't follow. You're talking just about the variable names in the get_highvar_genes function?

**Comment by dylkot** [comment]
Ahh I see what you mean, that case where numgenes isn't defined isn't accessible in practice but I still fixed the variable names like you suggested. Thanks!
