### ISSUE TITLE
Is there a way to run the cNMF package within R? 

### ISSUE THREAD

**Issue by diazh1987** [dylkot/cNMF#21]
I am very interested in applying this cNMF package to single cell datasets within the R programming language, 
 1) does a version of cNMF exist that is written in R? 
 2) can the current cNMF package be effectively accessed and run within the R programing environment?

**Comment by dylkot** [comment]
No, there doesn't unfortunately. However, I specify commands to run cNMF from the command line so you don't have to do any python coding yourself. You can just load the resulting text files into R to analyze them as you wish.
