### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by Rui-Jing** [dylkot/cNMF#22]
Hi,
Thanks for developing this user-friendly tool. I met an question when i runing the code : 
**python3 ./cNMF/cnmf.py prepare --output-dir ./output_cnmf/p121_2 --name p121_2 -c ./p121_2_counts.txt -k 4 5 6 7 8 9 10 11 12 13 --n-iter 300 --total-workers 8 --seed 14 --numgenes 2000**

**The error is ：**
/home/abc/miniconda3/envs/cnmf_env/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py:806: UserWarning: Revieved a view of an AnnData. Making a copy.
  view_to_actual(adata)
Traceback (most recent call last):
  File "./cNMF/cnmf.py", line 868, in <module>
    high_variance_genes_filter=highvargenes)
  File "./cNMF/cnmf.py", line 324, in get_norm_counts
    examples = norm_counts.obs.index[zerocells]
  File "/home/abc/miniconda3/envs/cnmf_env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4111, in __getitem__
    result = getitem(key)
**IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed**

I sincerely hope to get your kind help.

**Comment by jiapeiyuan17** [comment]
@Rui-Jing Have you soled the issue? I have encountered the same problem. And I encountered a trouble that when I wad trying to use it with a large file, it will give the error as below:
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

But if I only extract part of the file, it does work.

The count matrix file is (6343*36601), if I limit the files size do not exceed the size of (2000*36601), it works, but if I try the size of 3000*36601, it will give the error above.

**Comment by AteeqMKhaliq** [comment]
Hi, 
I got the exact same error, did you guys find any solutions to it?

**Comment by dylkot** [comment]
Hi all,

Sorry for being slow to reply here. Does anyone mind sending some example data I can use to reproduce the issue? It seems to be most likely an issue with data input. For example, are there any cells with 0 counts or genes with 0 counts? It would be good to filter those before running the prepare step. Again, very sorry for being slow to reply to this!

**Comment by dylkot** [comment]
So for @Rui-Jing's example, the problem is specifically because there are cells with 0 counts of any of the over-dispersed genes and the error comes when it is trying to print the list of cells this is true of. I am going to update the code so it correctly lists those cells. But the solution is to filter out cells with too few counts. For @AteeqMKhaliq, it seems you might be using an old version of cNMF, would you mind updating to the current master branch? But you seem to be having the exact same issue as @Rui-Jing

**Comment by dylkot** [comment]
The problem should now be fixed to print an informative error message that some of your cells don't have any counts for the selected overdispersed genes.

**Comment by rpauly** [comment]
I do not believe this issue is solved with the new issue. I am still getting the same issue.
