### ISSUE TITLE
How to comprehend the usage matrix for cells?

### ISSUE THREAD

**Issue by daisyyr** [dylkot/cNMF#23]
Hi authors!
Thanks for creating such a useful tool!
I have a question concerning the calculation of usage matrix.
1. Did you consider all of genes in the input matrix (that is highly variable genes) when imputing usage matrix? Will I get different results when using input matrixs including 2000 or 5000 highly variable genes ?
2. In your paper, I've read words as follows. 
_We hypothesized that we could infer activity GEPs directly from variation in single-cell expression profiles using matrix factorization. In this context, matrix factorization would model the gene expression data matrix as the product of two lower rank matrices, one encoding the relative contribution of each gene to each program, and a second specifying the proportions in which the programs are combined for each cell. We refer to the second matrix as a ‘usage’ matrix as it specifies how much each GEP is ‘used’ by each cell in the dataset_
What does "the proportions in which the programs are combined for each cell"  mean? It seems that the sum of all programs in a cell does not equal to 100%.

Looking forward to your reply.

**Comment by dylkot** [comment]
Thanks!
1. No the usage matrix is only calculated based on the highly variable genes. In general, yes the usage matrix will be different with different choices of the highly variable genes.
2. The default usage matrix outputted by cNMF is not normalized to sum to 1. In general the sum of usages for a cell is correlated with the sum of the normalized counts of highly variable genes (I.e. the sum of values for a cell in the matrix that is actually being factorized) which is in turn pretty decently correlated with the number of counts for the cell. We typically normalize the usage matrix to sum to 1 before analyzing it, to allow us to interpret the usages as proportions. 

I hope that helps!

**Comment by daisyyr** [comment]
> 

It really helps! Thanks a lot!
