### ISSUE TITLE
scikit-learn version and dtype issues

### ISSUE THREAD

**Issue by kijiy** [dylkot/cNMF#24]
Hi,

Thank you for the useful tool!
This is just a bug report, but `cnmf.py factorize` failed with scikit-learn v0.24.2. I found the keyword arguments alpha_H and alpha_W to `sklearn.decomposition.non_negative_factorization()` in several parts of the source code that may be supported only by scikit-learn v1. I updated scikit-learn and it worked. Though v0.23.2 is specified in the manual, it'd be better to fix that part if I'm correct.

Also, the dtype=float64 issue showed up again. Thanks to the previous discussions around #9, I put 

`norm_counts.X = norm_counts.X.astype(np.float64)`

to line 631 and now it's working.

**Comment by dylkot** [comment]
Hi, thanks for pointing this out! I reverted the master branch to the old version of the code before I updated to alpha_H so this should be fixed. I am planning an update to cnmf that will require the more recent version of scikit-learn but I will make sure the conda versioning is fixed before I update that. And thanks as well for the note about the dtype issue. That should be resolved with the roll-back as well.
