### ISSUE TITLE
when running consensus step, i got a ValueError

### ISSUE THREAD

**Issue by liaoshengyou** [dylkot/cNMF#25]
command:
python ./cNMF/cnmf.py consensus --output-dir subEpithelial --name subEpithelial_cNMF --components 10 --local-density-threshold 0.01 --show-clustering

Traceback (most recent call last):
  File "/softs/cNMF/cnmf.py", line 756, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering, args.stats_
  File "/softs/cNMF/cnmf.py", line 523, in consensus
    _, spectra_tpm = self._nmf(tpm.T, nmf_kwargs=fit_tpm_nmf_kwargs, topic_labels=np.arange(1,k+1))
  File "/softs/cNMF/cnmf.py", line 285, in _nmf
    (W, H, niter) = non_negative_factorization(X.values, **nmf_kwargs)
  File "/softs/conda/anaconda/envs/cnmf/lib/python3.6/site-packages/sklearn/decomposition/nmf.py", line 10orization
    _check_init(H, (n_components, n_features), "NMF (input H)")
  File "/softs/conda/anaconda/envs/cnmf/lib/python3.6/site-packages/sklearn/decomposition/nmf.py", line 60
    A = check_array(A)
  File "/softs/conda/anaconda/envs/cnmf/lib/python3.6/site-packages/sklearn/utils/validation.py", line 568
    allow_nan=force_all_finite == 'allow-nan')
  File "/softs/conda/anaconda/envs/cnmf/lib/python3.6/site-packages/sklearn/utils/validation.py", line 56,
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

this error i slove by edit cnmf.py:
line494:
norm_usages = rf_usages.div(rf_usages.sum(axis=1), axis=0)

changed:
norm_usages = rf_usages.div(rf_usages.sum(axis=1), axis=0)
norm_usages = norm_usages.fillna(0)

**Comment by dylkot** [comment]
Hi @liaoshengyou, thanks for using cNMF and for your comment. That makes sense but I wonder why are you getting NaNs in the usage matrix? Do you have some cells with 0 counts? I don't see why you should ever have rf_usages.sum(axis=1) that would equal 0. I'm worried that simply filling in the NaNs with 0 could be masking a bigger data input problem. Could you for example print out 

```
rf_usages.loc[rf_usages.isnull().sum(axis=1)>0, :]
```

so we can understand better what is going on?

**Comment by liaoshengyou** [comment]
> Hi @liaoshengyou, thanks for using cNMF and for your comment. That makes sense but I wonder why are you getting NaNs in the usage matrix? Do you have some cells with 0 counts? I don't see why you should ever have rf_usages.sum(axis=1) that would equal 0. I'm worried that simply filling in the NaNs with 0 could be masking a bigger data input problem. Could you for example print out
> 
> ```
> rf_usages.loc[rf_usages.isnull().sum(axis=1)>0, :]
> ```
> 
> so we can understand better what is going on?



thanks,  

i carefully check this value,
 in rf_usages ， mydata has no  NaN,  but running  follow step:
> norm_usages = rf_usages.div(rf_usages.sum(axis=1), axis=0) 

“norm_usages”  function variables has NaN value exists, 

print( norm_usages.loc[norm_usages.isnull().sum(axis=1)>0, :] ) as follow:

            1   2   3   4   5   6   7   8   9   10  11  12  13
AL645608.9 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AL137802.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AL365184.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC012511.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC016252.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC117395.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC079594.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC112250.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC106882.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AF250324.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC01385  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC02148  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC02530  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
CLPS       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
PGK2       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AL731661.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
CLDN34     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
HSFX3      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC087623.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AL138781.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
OR5M11     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AP002347.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
CARD17     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AP003027.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC078927.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC090680.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC025252.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AL356019.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC068446.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC120114.3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
...         ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
AC015813.8 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC090912.3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC01544  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC090398.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC068473.3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC010463.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC011465.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
ZSCAN5C    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AL359916.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
WFDC5      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AP001625.3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LARGE-IT1  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
TFDP3      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
GPR101     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
CRNN       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC017048.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC012668.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC122136.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC079612.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC093734.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC025871.3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
IFNK       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
IFIT1B     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC02697  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC02312  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC027020.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC009087.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC006213.5 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
AC008635.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
LINC01665  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

[121 rows x 13 columns]

**Comment by dylkot** [comment]
Oh weird, that is supposed to be a cells X programs matrix, not genes X programs. Is it possible you have the input data transposed? I.e. the input is supposed to be Cells X Genes. Are you inputting Genes X Cells?
