### ISSUE TITLE
when running consensus step, i got a  Aborted (core dumped) for qt platform

### ISSUE THREAD

**Issue by liaoshengyou** [dylkot/cNMF#26]
error log:

> This application failed to start because it could not find or load the Qt platform plugin "xcb"
> 
> Reinstalling the application may fix this problem.
> Aborted (core dumped)
> 

slove by:
>   conda install qt
>   conda install pyqt

and then  edit the cnmf.py, in the header add follow line
>   os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '/softs/conda/anaconda/plugins/platforms'
>   os.environ['FONTCONFIG_FILE'] = "/etc/fonts/fonts.conf"
>   os.environ['FONTCONFIG_PATH'] = "/etc/fonts/"

**Comment by dylkot** [comment]
Got it. I imagine this is a problem with conda not installing all of the proper dependencies. If this is a problem for other users I can look into adjusting the specifications. Thanks for posting this with the solution!
