### ISSUE TITLE
Is there a way to select an optimal K automatically?

### ISSUE THREAD

**Issue by smk5g5** [dylkot/cNMF#27]
Hi,

I was wondering if there is way to select K automatically rather than looking at the plot? If one were to go about doing it what would you suggest is the best way to do it?

Thanks 🙏

**Comment by dylkot** [comment]
Hi @smk5g5 -- thanks for your interest in cNMF. Unfortunately there isn't a single universally applicable way to automatically pick K (similarly to how there isn't one for PCA or KMeans). One approach I experimented with was the Jackstraw procedure which is implemented in Seurat for deciding on the number of PCs https://satijalab.org/seurat/reference/jackstraw. In my simulations and in some real datasets, the ideal number of cNMF components seemed to be 1 + the number of PCs determined by Jackstraw. However, the Jackstraw method does not always get the right value for the number of PCs (see the discussion here https://github.com/theislab/scanpy/issues/872). In any case, I hope this helps, and if you come up with a great solution, feel free to drop it in the response to this!
