### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by cubense** [dylkot/cNMF#30]
I am attempting to deploy a private instance. I am getting the following error

i can run my other data success, so i believe there is something wrong with my matrix.
code 
`replicate_spectra=df
l2_norms = (replicate_spectra**2).sum(axis=1).apply(np.sqrt)
l2_spectra = replicate_spectra.div(l2_norms, axis=0)
topics_dist = squareform(fast_euclidean(l2_spectra.values))
kmeans_model = KMeans(n_clusters=51, n_init=10, random_state=1)
kmeans_model.fit(l2_spectra)
kmeans_cluster_labels = pd.Series(kmeans_model.labels_+1, index=l2_spectra.index)
spectra_order = get_clustergram_ordering(topics_dist, kmeans_cluster_labels)
topics_dist = topics_dist[spectra_order, :][:, spectra_order]
kmeans_cluster_labels = kmeans_cluster_labels.iloc[spectra_order]

## Permute the cluster order so that the colors aren't sequential
permmap = get_shuffle(51, 5)
kmeans_cluster_labels_perm = kmeans_cluster_labels.apply(lambda x: permmap[x])        
(heatmapax, topax, leftax, heatmapfig, heatmapcbar, fig) = labeled_heatmap(topics_dist, kmeans_cluster_labels_perm.values,
                                                                      1, figsize=(3.,3.), dpi=300)
heatmapax.set_xlabel('NMF Components', fontsize=12)
leftax.set_ylabel('NMF Components', fontsize=12)
topax.set_title('Pre-filtered Clustering', fontsize=13)`

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_26520/2907498122.py in <module>
      6 kmeans_model.fit(l2_spectra)
      7 kmeans_cluster_labels = pd.Series(kmeans_model.labels_+1, index=l2_spectra.index)
----> 8 spectra_order = get_clustergram_ordering(topics_dist, kmeans_cluster_labels)
      9 topics_dist = topics_dist[spectra_order, :][:, spectra_order]
     10 kmeans_cluster_labels = kmeans_cluster_labels.iloc[spectra_order]

~\AppData\Local\Temp/ipykernel_26520/2720665459.py in get_clustergram_ordering(topic_dist, kmeans_cluster_labels)
      8         cl_dist = squareform(topics_dist[cl_filter, :][:, cl_filter])
      9         cl_dist[cl_dist < 0] = 0 #Rarely get floating point arithmetic issues
---> 10         cl_link = linkage(cl_dist, 'average')
     11         cl_leaves_order = leaves_list(cl_link)
     12 

E:\conda\miniconda\envs\cnmf_env\lib\site-packages\fastcluster.py in linkage(X, method, metric, preserve_input)
    243         X = pdist(X, metric=metric)
    244         X = array(X, dtype=double, copy=False, order='C', subok=True)
--> 245     Z = empty((N-1,4))
    246     if N > 1:
    247         linkage_wrap(N, X, Z, mthidx[method])

ValueError: negative dimensions are not allowed

whats wrong with my data? thank you!

**Comment by dylkot** [comment]
Hi @cubense - sorry I missed this! Are you still having this bug? Can you share the consensus command you are running that causes this issue?It looks like there might be a consensus cluster with no programs in it after filtering outliers, so maybe try setting density_threshold=2 and see if it runs?

**Comment by cubense** [comment]
> Hi @cubense - sorry I missed this! Are you still having this bug? Can you share the consensus command you are running that causes this issue?It looks like there might be a consensus cluster with no programs in it after filtering outliers, so maybe try setting density_threshold=2 and see if it runs?

Thank you for your reply!
In fact, I did this by copying this part of the source code from CodeOcean. I believed that the consensus cluster might be not found too. The reason could be that I tried to do it using the activity matrix of all genes and I did not try to run it again successfully.
Finally I used the default settings of  cNMF for the analysis and it worked well.
