### ISSUE TITLE
invalid value encountered in true_divide error

### ISSUE THREAD

**Issue by avishai987** [dylkot/cNMF#34]
Hi,
While running cnmf_obj.consensus on my data, I encountered this error:
cnmf.py:701: RuntimeWarning: invalid value encountered in true_divide
  norm_tpm = (np.array(tpm.X.todense()) - tpm_stats['__mean'].values) / tpm_stats['__std'].values
What causes this problem? 
thanks!

**Comment by avishai987** [comment]
Never mind, I think it's because I accidentally put TPM in count_fn instead of raw count.

**Comment by dylkot** [comment]
Thanks for the update!
