### ISSUE TITLE
Error at combining stage: invalid literal/lengths set

### ISSUE THREAD

**Issue by twoneu** [dylkot/cNMF#35]
Hi @dylkot,

Thank you for putting together a great tutorial for your cNMF package. I am encountering the following error at the `cnmf_obj.combine()` step:

`
Combining factorizations for k=5.
Combining factorizations for k=6.
Combining factorizations for k=7.
Combining factorizations for k=8.
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
/var/folders/sd/b0wjprrj19bdz5sw2smwp62m0000gq/T/ipykernel_73413/3939318147.py in <module>
----> 1 cnmf_obj.combine()

~/opt/anaconda3/lib/python3.9/site-packages/cnmf/cnmf.py in combine(self, components)
    373 
    374         for k in ks:
--> 375             self.combine_nmf(k)
    376 
    377 

~/opt/anaconda3/lib/python3.9/site-packages/cnmf/cnmf.py in combine_nmf(self, k, remove_individual_iterations)
    596         for i,p in run_params_subset.iterrows():
    597 
--> 598             spectra = load_df_from_npz(self.paths['iter_spectra'] % (p['n_components'], p['iter']))
    599             if combined_spectra is None:
    600                 combined_spectra = np.zeros((n_iter, k, spectra.shape[1]))

~/opt/anaconda3/lib/python3.9/site-packages/cnmf/cnmf.py in load_df_from_npz(filename)
     33 def load_df_from_npz(filename):
     34     with np.load(filename, allow_pickle=True) as f:
---> 35         obj = pd.DataFrame(**f)
     36     return obj
     37 

~/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/npyio.py in __getitem__(self, key)
    252             if magic == format.MAGIC_PREFIX:
    253                 bytes = self.zip.open(key)
--> 254                 return format.read_array(bytes,
    255                                          allow_pickle=self.allow_pickle,
    256                                          pickle_kwargs=self.pickle_kwargs)

~/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    773                     read_count = min(max_read_count, count - i)
    774                     read_size = int(read_count * dtype.itemsize)
--> 775                     data = _read_bytes(fp, read_size, "array data")
    776                     array[i:i+read_count] = numpy.frombuffer(data, dtype=dtype,
    777                                                              count=read_count)

~/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/format.py in _read_bytes(fp, size, error_template)
    902         # done about that.  note that regular files can't be non-blocking
    903         try:
--> 904             r = fp.read(size - len(data))
    905             data += r
    906             if len(r) == 0 or len(data) == size:

~/opt/anaconda3/lib/python3.9/zipfile.py in read(self, n)
    920         self._offset = 0
    921         while n > 0 and not self._eof:
--> 922             data = self._read1(n)
    923             if n < len(data):
    924                 self._readbuffer = data

~/opt/anaconda3/lib/python3.9/zipfile.py in _read1(self, n)
    996         elif self._compress_type == ZIP_DEFLATED:
    997             n = max(n, self.MIN_READ_SIZE)
--> 998             data = self._decompressor.decompress(data, n)
    999             self._eof = (self._decompressor.eof or
   1000                          self._compress_left <= 0 and

error: Error -3 while decompressing data: invalid literal/lengths set`

The factorize step ran successfully with no errors or warnings. When I run the combine step, it looks like it successfully combines factorizations for k=5 through k=7, but the error occurs when trying to combine factorizations for either k=8 or k=9. How should I best proceed?

**Comment by dylkot** [comment]
Hi, thank you for your comment and for using cNMF! Can you confirm that all of the individual iterations completed? You can look in cnmf_dir/name/cnmf_tmp and you should see output files for all of the jobs from k=7...k=9 (I.e. one for each NMF iteration) but maybe one or more are missing for k=8?

**Comment by shahrozeabbas** [comment]
> Hi, thank you for your comment and for using cNMF! Can you confirm that all of the individual iterations completed? You can look in cnmf_dir/name/cnmf_tmp and you should see output files for all of the jobs from k=7...k=9 (I.e. one for each NMF iteration) but maybe one or more are missing for k=8?

Hi, I don't have the same issue, but I do have an error with the `combine` method as well. It's throwing an error because some of the iteration files are missing. What's the reason for missing iteration files and how could I correct this? Thanks.

This is an example : 
`FileNotFoundError: [Errno 2] No such file or directory: cnmf_tmp/CDKi_cNMF.spectra.k_20.iter_1.df.npz'`

**Comment by dylkot** [comment]
Hi, sorry for slow reply. I added an option `skip_missing_files` for the combine method that will allow you to skip the missing files in the combine step.

cheers,
Dylan

**Comment by danafd** [comment]
Hello, Is the `skip_missing_files` available in command line? I'm running through the same problem.
