### ISSUE TITLE
use prenormalized matrix for cNMF

### ISSUE THREAD

**Issue by sumitava1992** [dylkot/cNMF#36]
hii i have a pre normalized matrix to compute NMF, if i want to use this matrix do i have to input both the "-c" parameter and "--tpm" in the cnmf prepare function?

**Comment by dylkot** [comment]
Hi @sumitava1992 - sorry for the slow reply. Do you want to use all of the genes in the prenormalized matrix? If not, you should indicate that you want to use all of the genes in the --num_genes argument. And are you okay with the fact that cNMF will  variance normalize the genes (in addition to whatever normalization you did)? I haven't implemented an argument to tell it not to do that currently. And then lastly the question is what scaling you want the data to be in when it refits the spectra. I think you likely would still want to submit a normalized tpm or tp10k matrix for the --tpm argument, and your prenormalized matrix to the -c argument. Hope that helps!

**Comment by minigel** [comment]
Sorry to reopen this closed issue -- are there plans to include an argument to skip variance normalization at this time? I'm also interested in using a prenormalized matrix (of non-gene expression data), and I'm not sure yet if an additional normalization step would be the right approach for this input data. Thank you!
