### ISSUE TITLE
jitdebug

### ISSUE THREAD

**Issue by wbf520qcp** [dylkot/cNMF#37]
Hello, thanks for this fantastic tool. I'm running cNMF on my single cell data but met with the error at cnmf prepare say that "TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug''. What was the problem here?

Thanks,
Bofei

**Comment by dylkot** [comment]
Hi Bofei,

Can you include the full error trace? That seems like it might be a system issue rather than a cNMF issue?

**Comment by wbf520qcp** [comment]
![Screen Shot 2022-06-27 at 11 47 57 PM](https://user-images.githubusercontent.com/56213252/176095172-976f6423-4d36-4845-a572-1e4dcaf643c8.png)
Here you go.

**Comment by dylkot** [comment]
OK so the issue is actually happening in scanpy's scale function. Is the data you are providing sparse or dense? If so, maybe try with the `--densify` flag in the prepare function

**Comment by wbf520qcp** [comment]
It's dense. But never mind. I got to run it on my local computer. So, good for now. Thanks
