### ISSUE TITLE
which matrix should NMF use in single cell RNA seq data to find diferential gene program?

### ISSUE THREAD

**Issue by hahia** [dylkot/cNMF#4]
Hi there,

I'm new to scRNA-seq(use the seurat pipeline to analysis) and nmf.

Recently, I'm going to do nmf in the scRNA-seq to find the diferent programs(like markers for some cells).

But I don't know which matrix should me use to do nmf, normalized counts or scaled counts?

And how to choose the factorization rank in nmf?

Does anyone have experiences? Thanks for your help!

**Comment by dylkot** [comment]
The input for the "counts" parameter should be raw counts. All of the scaling is done by the cNMF functions within the "prepare" step.

Choosing the rank is complicated and I discuss in detail in the discussion and methods sections of the paper: https://elifesciences.org/articles/43803
