### ISSUE TITLE
Log Transformation 

### ISSUE THREAD

**Issue by Sayyam-Shah** [dylkot/cNMF#44]
Hello,

Thank you for the amazing tool!

Will I see substantially worse results if I input log transformed tpm data?

**Comment by dylkot** [comment]
Apologies for the slow reply! I haven't looked in detail but in general I would expect yes. The method expects count data as the main input (used for cNMF) and optionally TPM input. I think with log transformed TPM data, the high variance gene detection would be off so you might want to input a list of your own HVGs as well. Also, the resulting program in TPM spectra would not be in the expected units, although I'm not sure if they would be less interpretable. Let me know how it looks. And sorry again for the slow response.

**Comment by Sayyam-Shah** [comment]
Thank you for getting back to me! That makes sense. I have been inputting the counts from the data slot of sctransform version 2 and observed amazing results. 

Thank you so much for the tool. I have not input my own list of HVGs but I'll consider it. I have still clustered using the HVGs from sctransform rather than cnmf. Will inputting my own list of HVGs potentially improve the signatures or is it meant for downstream analysis?
