### ISSUE TITLE
Running cNMF for multiple batches?

### ISSUE THREAD

**Issue by mdmanurung** [dylkot/cNMF#45]
Dear Dylan,

Do you have any recommendations for running cNMF for a dataset with multiple batches?
Does it make sense to run cNMF separately for each batch and then perform quantile normalization on the GEP matrix?

Regards,
Mikhael

**Comment by mdmanurung** [comment]
Hi Dylan,

That sounds great! May I have your email then?

Best regards,
Mikhael

**Comment by dylkot** [comment]
dylkot@gmail.com
