### ISSUE TITLE
cnmf 1.4 is not on pip

### ISSUE THREAD

**Issue by Jon-bioinfo** [dylkot/cNMF#46]
The latest version on pip seems to be 1.3.4 so the function cnmf_obj.load_results part of the tutorial cannot be used.

**Comment by Jon-bioinfo** [comment]
I guess ignore, it's there. I needed to restart python after updating or something.
Though the version numbers do mismatch.

**Comment by dylkot** [comment]
Hi @Jon-bioinfo - thanks for pointing this out. I'll make sure to fix the labeling issue.
