### ISSUE TITLE
Should we do scale before run cnmf?

### ISSUE THREAD

**Issue by Zifeng1995** [dylkot/cNMF#5]
hi, here some questions.
Compared with the code in your paper ,the PBMC tutorial did not do any normalize or scale before run cNMF. All your examples in your paper did TPM-scaled. 
Should we do scale before run cnmf? which method is better?

**Comment by dylkot** [comment]
Hi, all of the scaling is done for you within the "prepare" step so you do not need to scale separately first. The "counts" input file should contain raw un-normalized counts.
