### ISSUE TITLE
applying cNMF to multiple datasets?

### ISSUE THREAD

**Issue by erzakiev** [dylkot/cNMF#51]
How would you recommend to proceed with multiple samples? In the original manuscript, you conclude that it is better to perform any kind of batch correction before applying cNMF, correct?

**Comment by erzakiev** [comment]
Thanks for the response, Dylan!! I dropped you a message on gmail.

I tried to do this myself by calculating spectra for individual samples, following the instructions for handling individual samples, and then I hierarchically clustered the resulting spectra from each sample based on their cosine similarity; 
![hierarchical clustering of cNMF spectra](https://user-images.githubusercontent.com/13952639/196876191-025f3db2-0dc6-4f08-a05a-fcfafddb85e0.png)
I then chose a cutoff for the tree to be cut into (see the red line in the plot above), and for the resulting clusters of spectra I just averaged values for each gene and sorted the resulting values in decreasing order, giving me a ranked set of genes that I took only top 50 of to form _signatures_.

This makeshift approach has provided me with some interesting signatures, some of whom are corroborated by other methods, and also the pathway enrichments are also spot-on. 

I'll certainly try out the example code you're going to send me, but in the meantime I wonder if that was an unreasonable approach?

**Comment by AAAapollo** [comment]
I have same question about multi-dataset. And I used SCTransform to remove batch effect. Could I directly use SCT-assay-counts matrix as input?

**Comment by dylkot** [comment]
Just an update on this topic that the method to batch correct the data prior to cNMF is in the development branch at this time with an example of its use in the Tutorials folder. Give it a try if you are interested.

**Comment by Christopher-Dall** [comment]
Hi, wanted to follow up on this. I have multiple samples (treated, untreated). Looked in the tutorial folder for this method to batch correct but didn't see anything. Any way to post the harmony pre-processing for combining datasets or another way to correct data prior to cNMF? Thank you in advance!

**Comment by dylkot** [comment]
Hey Christopher, are you looking in the development branch?
GitHub - dylkot/cNMF at development<https://github.com/dylkot/cNMF/tree/development>

Cheers,
Dylan

From: Christopher-Dall ***@***.***>
Date: Tuesday, November 14, 2023 at 6:11 PM
To: dylkot/cNMF ***@***.***>
Cc: Kotliar, Dylan A ***@***.***>, Comment ***@***.***>
Subject: Re: [dylkot/cNMF] applying cNMF to multiple datasets? (Issue #51)

Hi, wanted to follow up on this. I have multiple samples (treated, untreated). Looked in the tutorial folder for this method to batch correct but didn't see anything. Any way to post the harmony pre-processing for combining datasets or another way to correct data prior to cNMF? Thank you in advance!

**Comment by Christopher-Dall** [comment]
That'll do it! Thank you!!

**Comment by dylkot** [comment]
Awesome. We plan to push this to the main branch soon. Cheers, Dylan

From: Christopher-Dall ***@***.***>
Date: Wednesday, November 15, 2023 at 7:13 AM
To: dylkot/cNMF ***@***.***>
Cc: Kotliar, Dylan A ***@***.***>, Comment ***@***.***>
Subject: Re: [dylkot/cNMF] applying cNMF to multiple datasets? (Issue #51)

That'll do it! Thank you!!
