### ISSUE TITLE
How to assess the similarity between programs across samples

### ISSUE THREAD

**Issue by Dragonlongzhilin** [dylkot/cNMF#52]
Hi cNMF team,
  Thanks for developing a nice tools! I extracted different programs in serveral samples and want to assess the program similarity. I noticed there are two gene expression program matrix (Zscore and TPM). Which expression matrix is suitable for calculating the correlation between programs in different samples.

**Comment by michelle-curtis** [comment]
Hi, thanks for your comment. It is effective to use either the Z-score or TPM spectra matrix to compare correlation across programs. However, if using the TPM matrix, you will want to variance-normalize it to allow genes expressed at different scales to contribute equally to the program correlations - gene variances have already been output in the tpm_stats file. We also suggest using either the union or intersection of the HVGs across samples for these comparisons, especially when using the var-normed TPM-spectra. The TPM spectra matrix tends to have more baseline correlation across the non-differentially expressed genes (whereas these genes will tend to have zero values in the Z-score matrix).

**Comment by dylkot** [comment]
Yes, like @michelle-curtis said, either can work. I think using the Z-score output by default seems to work the best. And also as Michelle said, good to subset to high variance genes
