### ISSUE TITLE
not found cnmf v1.4?

### ISSUE THREAD

**Issue by Dragonlongzhilin** [dylkot/cNMF#53]
When I install cnmf using pip and encounted a problem.
ERROR: Could not find a version that satisfies the requirement cnmf==1.4 (from versions: 1.3.0, 1.3.1, 1.3.2, 1.3.4)

**Comment by dylkot** [comment]
Hi, to specify the version 1.4 you should use 

```
pip install cnmf==1.4.1
```

Thanks
