### ISSUE TITLE
cNMF on full length scRNA-seq

### ISSUE THREAD

**Issue by avishai987** [dylkot/cNMF#54]
Hi Dylan, I was wondering- your tutorials show 10x data as an input, which is 5' scRNA-seq. What about full-length seq like smart-seq2? Because the counts there are less meaningful and must be normalized according to gene length. should I provide the counts plus my own TPM? or just TPM in "counts" argument?
Thanks!

P.S- I just found this in the article:
"However, for the [Tasic et al. (2016)] dataset, which is based on full-transcript sequencing rather than digital UMI counting, we variance-normalized high-variance genes from the TPM matrix directly rather than from the raw count matrix as in the other datasets."
But I am not sure how to implement this.

**Comment by Sayyam-Shah** [comment]
Hi, I know this is old but to variance normalize the TPM matrix, could you provide the same matrix into the --counts and --tpm slot?

**Comment by dylkot** [comment]
Hey all, sorry for slow reply. For @avishai987's initial question, I think the simplest argument is just to provide the FPKM or RPKM matrix as input for "counts" and let cNMF normalize it for the TPM input (I.e. don't provide anything for TPM)

@Sayyam-Shah, I don't understand your question. What is your goal?

**Comment by Sayyam-Shah** [comment]
Awesome, thank you! Sorry, you answered it. My question was very similar to the initial one. I was initially wondering if we wanted to variance normalize the TPM matrix, would this require providing it both into the --counts and --tpm slot.

 I'll try providing the FPKM or RPKM matrix into only the counts slot with my smart-seq data.  

Thank you so much!

**Comment by dylkot** [comment]
Yeah, since FPKM is already TPM normalized, its the same just providing it once or providing it to both --counts and --tpm
