### ISSUE TITLE
if a got a GEPs, how to calculate the usages across cells.

### ISSUE THREAD

**Issue by bioworker** [dylkot/cNMF#56]
Dear author,
Thank you for make the NMF available in scRNA!
I have finished the cNMF run for multiple samples, and got a couple of DEPs.  How can I calculate usages of sampleA of DEPs from sampleB?

**Comment by Sayyam-Shah** [comment]
I would recommend aucell by scoring the top 100 genes from the signature.

**Comment by bioworker** [comment]
Thanks a lot.

**Comment by dylkot** [comment]
Hi, sorry I know its probably no longer helpful but this is the subject of [our recent preprint](https://www.biorxiv.org/content/10.1101/2024.05.03.592310v1).
