### ISSUE TITLE
Difference between gene_spectra_score.k_3.dt_0_1.txt and spectra.k_3.dt_0_1.consensus.txt

### ISSUE THREAD

**Issue by Li-ZhiD** [dylkot/cNMF#59]
Can anyone tell me the difference between "gene_spectra_score.k_3.dt_0_1.txt" and "spectra.k_3.dt_0_1.consensus.txt"?
Positive and negative values are allowed in "gene_spectra_score.k_3.dt_0_1.txt" with all genes, but only positive values are allowed in "spectra.k_3.dt_0_1.consensus.txt" with gene number specified in command line.

**Comment by dylkot** [comment]
Hi,

The ```gene_spectra_score.k_3.dt_0_1.txt``` represents the contribution of each gene to each cGEP in Z-score units (mean centered and variance scaled). ```spectra.k_3.dt_0_1.consensus.txt``` is more of an intermediate file output that we don't typically use in downstream analysis. It is the median of the spectras that were learned directly by the NMF runs and that were then clustered together in the consensus step. As a result, it only includes high-variance genes, and the spectras were learned on variance normalized counts data so it is in variance normalized units. 

For most applications you should use the ```gene_spectra_tpm.k_3.dt_0_1.txt``` output which is in TPM units where each value reflects how much each gene contributes to the program in TPM units or the ```gene_spectra_score.k_3.dt_0_1.txt``` output as above.

In general, there isn't much you should be doing with the ```spectra.k_3.dt_0_1.consensus.txt``` output. I will consider removing it in a later version.
