### ISSUE TITLE
ImportError: libblosc.so.1

### ISSUE THREAD

**Issue by Zifeng1995** [dylkot/cNMF#6]
Recently, I  created cnmf_env following the tutorial ,but met the error as followed.
![image](https://user-images.githubusercontent.com/53402047/84595285-9c0be800-ae89-11ea-9928-d1224f555cab.png)
Can you help me?

**Comment by dylkot** [comment]
This seems to be an issue with Scanpy as far as I can tell and I see you just opened an issue there about it. Hopefully they can address it.

What kind of computer/server are you using? I would try to check if libblosc.so.1 is in fact installed
