### ISSUE TITLE
Is it possible to exclude genes from the high-variance genes ?

### ISSUE THREAD

**Issue by kaizen89** [dylkot/cNMF#62]
Hi,
In my analyses I usually exclude genes that I consider as Junk and not biologically meaningful. Is there a way to exclude such genes contained in a text file so they are not considered among the high-variance ones or even better to manually assign a custom list of variable genes foud using Seurat as high variance?
Thanks a lot

**Comment by dylkot** [comment]
Hi @kaizen89, yes you can provide a user-specified gene list with ```genes_file``` argument in cnmf_obj.prepare() or the --genes-file argument on the command line.
