### ISSUE TITLE
Question about negative value in gep_scores matrix

### ISSUE THREAD

**Issue by Tang-RH** [dylkot/cNMF#64]
Dear authors:
    Thank you for your work on developing the nice tool cNMF.
    When I run the PBMC tutorial [https://github.com/dylkot/cNMF/blob/master/Tutorials/analyze_pbmc_example_data.ipynb](url), I found that  the gep_score ,the result matrix to select top genes in a GEP, had some negative values. And I saw the similar result in my own data.
![image](https://user-images.githubusercontent.com/89056018/234560847-9ae94411-faf0-42a5-b2fc-d9a6b695122a.png)
    I want to confirm that if the gep_score matrix is one of the nmf result matrixes. If so, why there are some negative values in it. If not, what is it, and why can we use it to select the top genes in a GEP?

**Comment by dylkot** [comment]
Hi, gep_score is actually not produced directly by NMF. It is produced by performing ordinary least square regression to predict the each gene but in mean-centered, standard deviation normalized units. So it is expected to have negative values.
