### ISSUE TITLE
Replace deprecated `sc.pp.normalize_per_cell` with `sc.pp.normalize_total`

### ISSUE THREAD

**Issue by scottgigante-immunai** [dylkot/cNMF#67]
`normalize_per_cell` raises `numpy.core._exceptions.UFuncTypeError` (see https://github.com/scverse/scanpy/issues/2500) and is deprecated.

**Comment by dylkot** [comment]
Hi @scottgigante-immunai I fixed this on the development branch using sc.pp.normalize_total() as was suggested and will update it to the main and pypi in the next week. Thanks!
