### ISSUE TITLE
Fcntl.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

### ISSUE THREAD

**Issue by Zifeng1995** [dylkot/cNMF#7]
When I run the code as `nohup parallel python /sibcb1/mxqianlab1/zfli/apps/cNMF/cnmf.py factorize --output-dir /sibcb1/mxqianlab1/zfli/MM_analysis/cnmf/filter_tumor/ZHQG_tumor --name ZHQG --worker-index {} ::: 0 1 2 3 4 5 6 7 8 9 10 11,` the nohup.out always report `Fcntl.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)`.
Can you help me with this issue?

**Comment by dylkot** [comment]
does it work without parallel? My guess is if the prepare step doesn't work (because of the previous issue) this won't work either

**Comment by Zifeng1995** [comment]
> 它可以并行运行吗？我的猜测是，如果准备步骤不起作用（由于上一期问题），这也将不起作用

The prepare step seemed to be working because I got some outputs and no error reported.
![image](https://user-images.githubusercontent.com/53402047/84897889-ec2cb980-b0d8-11ea-9769-ba05132780a9.png)
I followed your advice to remove parallel command, it worked! The problem seemed to be the parallel command. Thank you very much!!!!!
