### ISSUE TITLE
Usages matrix is empty

### ISSUE THREAD

**Issue by ccruizm** [dylkot/cNMF#76]
Good day, 

I am using cNMF in 10x scRNA data and run the whole pipeline without any problem, and the outputs look good except for the consensus matrix which is empty and only returns the cells and programs.

I am trying to figure out what the issue can be. I have read several issues in GitHub related to errors when there are low gene counts or cells that do not express any of the overdispersed genes, but in my case, I do not get any error, but all files are output by `cnmf consensus` with the drawback of the usage matrix. Attached is the output, so maybe you can help me understand where the problem relies.

Thanks in advance!
[output_ngenes5000_niter100_ruiz.gene_spectra_tpm.k_17.dt_0_02.txt](https://github.com/dylkot/cNMF/files/13706900/output_ngenes5000_niter100_ruiz.gene_spectra_tpm.k_17.dt_0_02.txt)
[output_ngenes5000_niter100_ruiz.spectra.k_17.dt_0_02.consensus.txt](https://github.com/dylkot/cNMF/files/13706901/output_ngenes5000_niter100_ruiz.spectra.k_17.dt_0_02.consensus.txt)
[output_ngenes5000_niter100_ruiz.usages.k_17.dt_0_02.consensus.txt](https://github.com/dylkot/cNMF/files/13706902/output_ngenes5000_niter100_ruiz.usages.k_17.dt_0_02.consensus.txt)

![output_ngenes5000_niter100_ruiz clustering k_17 dt_0_02](https://github.com/dylkot/cNMF/assets/37718031/054425eb-41d6-4a27-ab22-a2d33a1928e5)
[output_ngenes5000_niter100_ruiz.gene_spectra_score.k_17.dt_0_02.txt](https://github.com/dylkot/cNMF/files/13706899/output_ngenes5000_niter100_ruiz.gene_spectra_score.k_17.dt_0_02.txt)

**Comment by ccruizm** [comment]
I have dug a bit into the source of the issue, and I found that the step for refitting the usage is causing the problem. When in set `refit_usage=False` I get the usages matrix. I still have not understood why the refit_usage is giving an empty matrix. If you can provide any insights, it will be greatly appreciated.

**Comment by dylkot** [comment]
Hi, sorry for slow reply. Can you copy your full consensus command? Does the problem persist when you use why are you using such a low threshold for density_threshold? Does the problem persist if you use density_threshold=0.15 which seems more appropriate based on the histogram?
