### ISSUE TITLE
Usage sum of each cell is over 1

### ISSUE THREAD

**Issue by juneE-cloud** [dylkot/cNMF#77]
Thank you for creating this excellent package!

Following the provided tutorial (analyze_pbmc_example_data.ipynb), I successfully reproduced nearly all the results in my jupyter notebook, however, surprisingly, I found that the file "pbmc_cNMF.usages.k_7.dt_0_1.consensus.txt" showed extremely low usage (see below).

According to the tutorial, this matrix should be normalized to sum to 1, but I observed some values are over 1.

<img width="834" alt="DA97E07E-5F3B-4312-9390-AB7C98AC2FEC" src="https://github.com/dylkot/cNMF/assets/84324404/d68a5323-ea2e-430f-aa65-235a01e75f2e">

<img width="815" alt="05CE5473-0C74-4FAD-A3BD-705B613B0003" src="https://github.com/dylkot/cNMF/assets/84324404/85784cdd-0cca-42ad-8aa0-21f08e15d319">

Is it correct?

Looking for your kind reply.

Happy Christmas Eve, btw :)

**Comment by juneE-cloud** [comment]
This matrix seemed to be normalized, but I’m not sure.

**Comment by LiuCanidk** [comment]
Hi, did you figure that out? I also notice that there were some extreme values in my usage matrix, which made the visualization strange.

**Comment by juneE-cloud** [comment]
> Hi, did you figure that out? I also notice that there were some extreme values in my usage matrix, which made the visualization strange.

I used the previous version that worked for me:)

**Comment by dylkot** [comment]
Hi apologies for the confusion. In the current master branch ```cnmf_obj.load_results()``` returns unnormalized usages. However, in the current development branch, it defaults to returning normalized usages but this can be controlled with a parameter:

```
cnmf_obj.load_results(self, K, density_threshold, n_top_genes=100, norm_usage = True)
```

I hope this helps!
