### ISSUE TITLE
Variance Normalization

### ISSUE THREAD

**Issue by Sayyam-Shah** [dylkot/cNMF#78]
Hi!

Sorry, I just want to make sure, the matrix that gets fed into the --tpm slot gets variance normalized?

**Comment by dylkot** [comment]
Hi @Sayyam-Shah, the matrix that gets fed into the --tpm slot does NOT get normalized. It is there to fit the spectra in TPM units so it isn't normalized. The matrix that gets fed into the --counts slot does get normalized though.
