### ISSUE TITLE
Seurat integration

### ISSUE THREAD

**Issue by DiegoSafian** [dylkot/cNMF#80]
HI,

I was wondering if there is an advisable way to incorporate the usage result into a Seurat object (ideally V5), so that one can calculate the usage of GEP per cell cluster and plot the data in DimPlot or as heatmap??

Kind regards,
Diego

**Comment by dylkot** [comment]
Hi Diego, I'm not an expert in Seurat but I think you can use something like this:

https://satijalab.github.io/seurat-object/reference/AddMetaData.html

```
library(Seurat)
seurat_obj <- AddMetaData(object = seurat_obj, metadata = usage_df)
```

I hope that helps!
