### ISSUE TITLE
the sign "&" in cNMF parallelization

### ISSUE THREAD

**Issue by LiuCanidk** [dylkot/cNMF#82]
Hi @dylkot 
In the tutorial (README.md), there was the sign "&" in the _Running cNMF_ section, but in the _Step by step guide_ section, no "&"
Should I add the sign "&" in the parallel factorization step?

> cnmf factorize --output-dir ./example_data --name example_cNMF --worker-index 0 --total-workers 3 &
cnmf factorize --output-dir ./example_data --name example_cNMF --worker-index 1 --total-workers 3 &
cnmf factorize --output-dir ./example_data --name example_cNMF --worker-index 2 --total-workers 3 &

OR?
> cnmf factorize --output-dir ./example_data --name example_cNMF --worker-index 0 --total-workers 3
cnmf factorize --output-dir ./example_data --name example_cNMF --worker-index 1 --total-workers 3
cnmf factorize --output-dir ./example_data --name example_cNMF --worker-index 2 --total-workers 3
...

**Comment by LiuCanidk** [comment]
In fact, I missed the "&", but it worked fine in the command line, but I found some weird results (see below), so I doubt if there is any problem with my code here.
![image](https://github.com/dylkot/cNMF/assets/99864079/f22cc395-ebb6-486b-b438-3ca230decca1)

![image](https://github.com/dylkot/cNMF/assets/99864079/8f12426f-57a2-4b3c-bc48-0fcda37294c7)
as you see, although the clustering result is very robust, the GEP usage in clusters did not seem right, for the last 3 GEPs.

**Comment by dylkot** [comment]
Hi, the & at the end of the line causes it to run in the background so that you can submit many commands sequentially without waiting for each one to finish.
