### ISSUE TITLE
preprocess argument bug

### ISSUE THREAD

**Issue by avishai987** [dylkot/cNMF#86]
Hi, thanks for adding batch effect correction to the software. 
I think I just found a bug- 
in preprocess_for_cnmf function, theta is passed to self.normalize_batchcorrect function, but not to self.harmony_correct_X (in line 318 preprocess.py), which there it should affect. So theta is always 1 even if you specify otherwise.
Thanks,
Avishai

**Comment by dylkot** [comment]
thanks for pointing this out. I've never messed with the theta variable so I didn't notice. It should be fixed on the development branch now.
