### ISSUE TITLE
Batch correction error

### ISSUE THREAD

**Issue by ChoiJi-Hye** [dylkot/cNMF#92]
Hi! Thanks for creating such a useful tool!

I might have a simple question, but since I'm an R and Seurat user and not very familiar with Python and Anndata, I need some help.

I'm processing data with Seurat and then trying to use cNMF for batch correction. While the non-batch corrected parts are working fine, the batch correction part is causing issues.

After converting my Seurat object to Anndata and proceeding with batch correction, I encountered the following error:

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/3a72589b-11fb-410d-ae75-2b2b4fdc28c3">

I tried converting the data to counts before proceeding, but I still receive the "Not integer" error.
```
pbmc[['RNA']]@data <- pbmc[['RNA']]@counts
SaveH5Seurat(pbmc, filename = "pbmc.h5Seurat")
Convert("pbmc.h5Seurat", dest = "h5ad")
```

```
from cnmf import cNMF, Preprocess
p = Preprocess(random_seed=14)
(adata_c, adata_tpm, hvgs) = p.preprocess_for_cnmf(pbmc, harmony_vars=['Sample'], n_top_rna_genes = 2000, librarysize_targetsum= 1e6, save_output_base='./batchcorrect_Sample')
```
I would appreciate any guidance on how to resolve this issue and properly perform batch correction with cNMF.

Thank you!
Ji Hye Choi

**Comment by dylkot** [comment]
Hi @ChoiJi-Hye,

I believe the data you are exporting from Seurat is not the count-level data but maybe normalized data. The cNMF pipeline expects the input data to be counts. Could you just check in python:

```
pbmc.X[:20, :20]
```

to see what the data looks like?

**Comment by ChoiJi-Hye** [comment]
I'm so grateful for your quick response!
As you mentioned, I checked adata.X and found that it contained floating-point numbers instead of integers.
After creating a new Seurat object and converting it to AnnData, everything worked perfectly!

Thank you for creating such a useful tool and for your prompt help once again!
Ji Hye Choi

**Comment by ChoiJi-Hye** [comment]
I'm so grateful for your quick response!
As you mentioned, I checked adata.X and found that it contained floating-point numbers instead of integers.
After creating a new Seurat object from scratch and converting it to AnnData, everything worked perfectly!

Thank you for creating such a useful tool and for your prompt help once again!
Ji Hye Choi
